# coding: utf-8

"""


    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import urllib3

import launch.api_client
from launch.api_client import api_client, configuration, schemas
from launch.api_client.paths.v1_llm_fine_tunes_fine_tune_id_cancel import (  # noqa: E501
    put,
)

from .. import ApiTestMixin


class TestV1LlmFineTunesFineTuneIdCancel(ApiTestMixin, unittest.TestCase):
    """
    V1LlmFineTunesFineTuneIdCancel unit test stubs
        Cancel Fine Tune  # noqa: E501
    """

    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = put.ApiForput(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    response_status = 200


if __name__ == "__main__":
    unittest.main()
