# coding: utf-8

"""
    launch

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import uuid  # noqa: F401
from datetime import date, datetime  # noqa: F401

import frozendict  # noqa: F401
import typing_extensions  # noqa: F401

from launch.api_client import schemas  # noqa: F401


class BatchCompletionsJob(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        required = {
            "completed_at",
            "metadata",
            "expires_at",
            "model_config",
            "job_id",
            "created_at",
            "output_data_path",
            "status",
        }
        
        class properties:
            job_id = schemas.StrSchema
            output_data_path = schemas.StrSchema
        
            @staticmethod
            def model_config() -> typing.Type['BatchCompletionsModelConfig']:
                return BatchCompletionsModelConfig
        
            @staticmethod
            def status() -> typing.Type['BatchCompletionsJobStatus']:
                return BatchCompletionsJobStatus
            created_at = schemas.StrSchema
            expires_at = schemas.StrSchema
            
            
            class completed_at(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'completed_at':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class metadata(
                schemas.DictBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneFrozenDictMixin
            ):
            
            
                class MetaOapg:
                    additional_properties = schemas.StrSchema
            
                
                def __getitem__(self, name: typing.Union[str, ]) -> MetaOapg.additional_properties:
                    # dict_instance[name] accessor
                    return super().__getitem__(name)
                
                def get_item_oapg(self, name: typing.Union[str, ]) -> MetaOapg.additional_properties:
                    return super().get_item_oapg(name)
            
                def __new__(
                    cls,
                    *_args: typing.Union[dict, frozendict.frozendict, None, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                    **kwargs: typing.Union[MetaOapg.additional_properties, str, ],
                ) -> 'metadata':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                        **kwargs,
                    )
            
            
            class input_data_path(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'input_data_path':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class priority(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'priority':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            __annotations__ = {
                "job_id": job_id,
                "output_data_path": output_data_path,
                "model_config": model_config,
                "status": status,
                "created_at": created_at,
                "expires_at": expires_at,
                "completed_at": completed_at,
                "metadata": metadata,
                "input_data_path": input_data_path,
                "priority": priority,
            }
    
    completed_at: MetaOapg.properties.completed_at
    metadata: MetaOapg.properties.metadata
    expires_at: MetaOapg.properties.expires_at
    model_config: 'BatchCompletionsModelConfig'
    job_id: MetaOapg.properties.job_id
    created_at: MetaOapg.properties.created_at
    output_data_path: MetaOapg.properties.output_data_path
    status: 'BatchCompletionsJobStatus'
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["job_id"]) -> MetaOapg.properties.job_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["output_data_path"]) -> MetaOapg.properties.output_data_path: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["model_config"]) -> 'BatchCompletionsModelConfig': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["status"]) -> 'BatchCompletionsJobStatus': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["created_at"]) -> MetaOapg.properties.created_at: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["expires_at"]) -> MetaOapg.properties.expires_at: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["completed_at"]) -> MetaOapg.properties.completed_at: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["metadata"]) -> MetaOapg.properties.metadata: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["input_data_path"]) -> MetaOapg.properties.input_data_path: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["priority"]) -> MetaOapg.properties.priority: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["job_id", "output_data_path", "model_config", "status", "created_at", "expires_at", "completed_at", "metadata", "input_data_path", "priority", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["job_id"]) -> MetaOapg.properties.job_id: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["output_data_path"]) -> MetaOapg.properties.output_data_path: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["model_config"]) -> 'BatchCompletionsModelConfig': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["status"]) -> 'BatchCompletionsJobStatus': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["created_at"]) -> MetaOapg.properties.created_at: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["expires_at"]) -> MetaOapg.properties.expires_at: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["completed_at"]) -> MetaOapg.properties.completed_at: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["metadata"]) -> MetaOapg.properties.metadata: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["input_data_path"]) -> typing.Union[MetaOapg.properties.input_data_path, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["priority"]) -> typing.Union[MetaOapg.properties.priority, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["job_id", "output_data_path", "model_config", "status", "created_at", "expires_at", "completed_at", "metadata", "input_data_path", "priority", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        completed_at: typing.Union[MetaOapg.properties.completed_at, None, str, ],
        metadata: typing.Union[MetaOapg.properties.metadata, dict, frozendict.frozendict, None, ],
        expires_at: typing.Union[MetaOapg.properties.expires_at, str, ],
        model_config: 'BatchCompletionsModelConfig',
        job_id: typing.Union[MetaOapg.properties.job_id, str, ],
        created_at: typing.Union[MetaOapg.properties.created_at, str, ],
        output_data_path: typing.Union[MetaOapg.properties.output_data_path, str, ],
        status: 'BatchCompletionsJobStatus',
        input_data_path: typing.Union[MetaOapg.properties.input_data_path, None, str, schemas.Unset] = schemas.unset,
        priority: typing.Union[MetaOapg.properties.priority, None, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'BatchCompletionsJob':
        return super().__new__(
            cls,
            *_args,
            completed_at=completed_at,
            metadata=metadata,
            expires_at=expires_at,
            model_config=model_config,
            job_id=job_id,
            created_at=created_at,
            output_data_path=output_data_path,
            status=status,
            input_data_path=input_data_path,
            priority=priority,
            _configuration=_configuration,
            **kwargs,
        )

from launch.api_client.model.batch_completions_job_status import (
    BatchCompletionsJobStatus,
)
from launch.api_client.model.batch_completions_model_config import (
    BatchCompletionsModelConfig,
)
