# coding: utf-8

"""
    launch

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from launch.api_client import schemas  # noqa: F401


class ChatCompletionTokenLogprob(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        required = {
            "top_logprobs",
            "logprob",
            "bytes",
            "token",
        }
        
        class properties:
            token = schemas.StrSchema
            logprob = schemas.NumberSchema
            
            
            class bytes(
                schemas.ListBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneTupleMixin
            ):
            
            
                class MetaOapg:
                    items = schemas.IntSchema
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[list, tuple, None, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'bytes':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class top_logprobs(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['TopLogprob']:
                        return TopLogprob
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple['TopLogprob'], typing.List['TopLogprob']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'top_logprobs':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'TopLogprob':
                    return super().__getitem__(i)
            __annotations__ = {
                "token": token,
                "logprob": logprob,
                "bytes": bytes,
                "top_logprobs": top_logprobs,
            }
    
    top_logprobs: MetaOapg.properties.top_logprobs
    logprob: MetaOapg.properties.logprob
    bytes: MetaOapg.properties.bytes
    token: MetaOapg.properties.token
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["token"]) -> MetaOapg.properties.token: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["logprob"]) -> MetaOapg.properties.logprob: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["bytes"]) -> MetaOapg.properties.bytes: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["top_logprobs"]) -> MetaOapg.properties.top_logprobs: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["token", "logprob", "bytes", "top_logprobs", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["token"]) -> MetaOapg.properties.token: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["logprob"]) -> MetaOapg.properties.logprob: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["bytes"]) -> MetaOapg.properties.bytes: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["top_logprobs"]) -> MetaOapg.properties.top_logprobs: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["token", "logprob", "bytes", "top_logprobs", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        top_logprobs: typing.Union[MetaOapg.properties.top_logprobs, list, tuple, ],
        logprob: typing.Union[MetaOapg.properties.logprob, decimal.Decimal, int, float, ],
        bytes: typing.Union[MetaOapg.properties.bytes, list, tuple, None, ],
        token: typing.Union[MetaOapg.properties.token, str, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ChatCompletionTokenLogprob':
        return super().__new__(
            cls,
            *_args,
            top_logprobs=top_logprobs,
            logprob=logprob,
            bytes=bytes,
            token=token,
            _configuration=_configuration,
            **kwargs,
        )

from launch.api_client.model.top_logprob import TopLogprob
