# coding: utf-8

"""
    launch

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from launch.api_client import schemas  # noqa: F401


class CompletionTokensDetails(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
            accepted_prediction_tokens = schemas.IntSchema
            audio_tokens = schemas.IntSchema
            reasoning_tokens = schemas.IntSchema
            rejected_prediction_tokens = schemas.IntSchema
            __annotations__ = {
                "accepted_prediction_tokens": accepted_prediction_tokens,
                "audio_tokens": audio_tokens,
                "reasoning_tokens": reasoning_tokens,
                "rejected_prediction_tokens": rejected_prediction_tokens,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["accepted_prediction_tokens"]) -> MetaOapg.properties.accepted_prediction_tokens: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["audio_tokens"]) -> MetaOapg.properties.audio_tokens: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["reasoning_tokens"]) -> MetaOapg.properties.reasoning_tokens: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["rejected_prediction_tokens"]) -> MetaOapg.properties.rejected_prediction_tokens: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["accepted_prediction_tokens", "audio_tokens", "reasoning_tokens", "rejected_prediction_tokens", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["accepted_prediction_tokens"]) -> typing.Union[MetaOapg.properties.accepted_prediction_tokens, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["audio_tokens"]) -> typing.Union[MetaOapg.properties.audio_tokens, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["reasoning_tokens"]) -> typing.Union[MetaOapg.properties.reasoning_tokens, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["rejected_prediction_tokens"]) -> typing.Union[MetaOapg.properties.rejected_prediction_tokens, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["accepted_prediction_tokens", "audio_tokens", "reasoning_tokens", "rejected_prediction_tokens", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        accepted_prediction_tokens: typing.Union[MetaOapg.properties.accepted_prediction_tokens, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        audio_tokens: typing.Union[MetaOapg.properties.audio_tokens, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        reasoning_tokens: typing.Union[MetaOapg.properties.reasoning_tokens, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        rejected_prediction_tokens: typing.Union[MetaOapg.properties.rejected_prediction_tokens, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'CompletionTokensDetails':
        return super().__new__(
            cls,
            *_args,
            accepted_prediction_tokens=accepted_prediction_tokens,
            audio_tokens=audio_tokens,
            reasoning_tokens=reasoning_tokens,
            rejected_prediction_tokens=rejected_prediction_tokens,
            _configuration=_configuration,
            **kwargs,
        )
