# coding: utf-8

"""
    launch

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from launch.api_client import schemas  # noqa: F401


class CreateBatchCompletionsV1ModelConfig(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        required = {
            "model",
        }
        
        class properties:
            model = schemas.StrSchema
            
            
            class max_model_len(
                schemas.IntBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneDecimalMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, decimal.Decimal, int, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'max_model_len':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class max_num_seqs(
                schemas.IntBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneDecimalMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, decimal.Decimal, int, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'max_num_seqs':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class enforce_eager(
                schemas.BoolBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneBoolMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, bool, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'enforce_eager':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class trust_remote_code(
                schemas.BoolBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneBoolMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, bool, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'trust_remote_code':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class pipeline_parallel_size(
                schemas.IntBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneDecimalMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, decimal.Decimal, int, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'pipeline_parallel_size':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class tensor_parallel_size(
                schemas.IntBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneDecimalMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, decimal.Decimal, int, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'tensor_parallel_size':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class quantization(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'quantization':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class disable_log_requests(
                schemas.BoolBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneBoolMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, bool, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'disable_log_requests':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class chat_template(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'chat_template':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class tool_call_parser(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'tool_call_parser':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class enable_auto_tool_choice(
                schemas.BoolBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneBoolMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, bool, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'enable_auto_tool_choice':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class load_format(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'load_format':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class config_format(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'config_format':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class tokenizer_mode(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'tokenizer_mode':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class limit_mm_per_prompt(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'limit_mm_per_prompt':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class max_num_batched_tokens(
                schemas.IntBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneDecimalMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, decimal.Decimal, int, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'max_num_batched_tokens':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class tokenizer(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'tokenizer':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class dtype(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'dtype':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class seed(
                schemas.IntBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneDecimalMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, decimal.Decimal, int, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'seed':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class revision(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'revision':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class code_revision(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'code_revision':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class rope_scaling(
                schemas.DictBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneFrozenDictMixin
            ):
            
            
                class MetaOapg:
                    additional_properties = schemas.AnyTypeSchema
            
                
                def __getitem__(self, name: typing.Union[str, ]) -> MetaOapg.additional_properties:
                    # dict_instance[name] accessor
                    return super().__getitem__(name)
                
                def get_item_oapg(self, name: typing.Union[str, ]) -> MetaOapg.additional_properties:
                    return super().get_item_oapg(name)
            
                def __new__(
                    cls,
                    *_args: typing.Union[dict, frozendict.frozendict, None, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                    **kwargs: typing.Union[MetaOapg.additional_properties, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
                ) -> 'rope_scaling':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                        **kwargs,
                    )
            
            
            class tokenizer_revision(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'tokenizer_revision':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class quantization_param_path(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'quantization_param_path':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class max_seq_len_to_capture(
                schemas.IntBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneDecimalMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, decimal.Decimal, int, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'max_seq_len_to_capture':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class disable_sliding_window(
                schemas.BoolBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneBoolMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, bool, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'disable_sliding_window':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class skip_tokenizer_init(
                schemas.BoolBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneBoolMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, bool, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'skip_tokenizer_init':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class served_model_name(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'served_model_name':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class override_neuron_config(
                schemas.DictBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneFrozenDictMixin
            ):
            
            
                class MetaOapg:
                    additional_properties = schemas.AnyTypeSchema
            
                
                def __getitem__(self, name: typing.Union[str, ]) -> MetaOapg.additional_properties:
                    # dict_instance[name] accessor
                    return super().__getitem__(name)
                
                def get_item_oapg(self, name: typing.Union[str, ]) -> MetaOapg.additional_properties:
                    return super().get_item_oapg(name)
            
                def __new__(
                    cls,
                    *_args: typing.Union[dict, frozendict.frozendict, None, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                    **kwargs: typing.Union[MetaOapg.additional_properties, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
                ) -> 'override_neuron_config':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                        **kwargs,
                    )
            
            
            class mm_processor_kwargs(
                schemas.DictBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneFrozenDictMixin
            ):
            
            
                class MetaOapg:
                    additional_properties = schemas.AnyTypeSchema
            
                
                def __getitem__(self, name: typing.Union[str, ]) -> MetaOapg.additional_properties:
                    # dict_instance[name] accessor
                    return super().__getitem__(name)
                
                def get_item_oapg(self, name: typing.Union[str, ]) -> MetaOapg.additional_properties:
                    return super().get_item_oapg(name)
            
                def __new__(
                    cls,
                    *_args: typing.Union[dict, frozendict.frozendict, None, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                    **kwargs: typing.Union[MetaOapg.additional_properties, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
                ) -> 'mm_processor_kwargs':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                        **kwargs,
                    )
            
            
            class block_size(
                schemas.IntBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneDecimalMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, decimal.Decimal, int, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'block_size':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class gpu_memory_utilization(
                schemas.NumberBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneDecimalMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, decimal.Decimal, int, float, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'gpu_memory_utilization':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class swap_space(
                schemas.NumberBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneDecimalMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, decimal.Decimal, int, float, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'swap_space':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class cache_dtype(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'cache_dtype':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class num_gpu_blocks_override(
                schemas.IntBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneDecimalMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, decimal.Decimal, int, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'num_gpu_blocks_override':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class enable_prefix_caching(
                schemas.BoolBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneBoolMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, bool, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'enable_prefix_caching':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class checkpoint_path(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'checkpoint_path':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class num_shards(
                schemas.IntBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneDecimalMixin
            ):
            
            
                class MetaOapg:
                    inclusive_minimum = 1
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, decimal.Decimal, int, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'num_shards':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class max_context_length(
                schemas.IntBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneDecimalMixin
            ):
            
            
                class MetaOapg:
                    inclusive_minimum = 1
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, decimal.Decimal, int, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'max_context_length':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class response_role(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'response_role':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class labels(
                schemas.DictSchema
            ):
            
            
                class MetaOapg:
                    additional_properties = schemas.StrSchema
                
                def __getitem__(self, name: typing.Union[str, ]) -> MetaOapg.additional_properties:
                    # dict_instance[name] accessor
                    return super().__getitem__(name)
                
                def get_item_oapg(self, name: typing.Union[str, ]) -> MetaOapg.additional_properties:
                    return super().get_item_oapg(name)
            
                def __new__(
                    cls,
                    *_args: typing.Union[dict, frozendict.frozendict, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                    **kwargs: typing.Union[MetaOapg.additional_properties, str, ],
                ) -> 'labels':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                        **kwargs,
                    )
            __annotations__ = {
                "model": model,
                "max_model_len": max_model_len,
                "max_num_seqs": max_num_seqs,
                "enforce_eager": enforce_eager,
                "trust_remote_code": trust_remote_code,
                "pipeline_parallel_size": pipeline_parallel_size,
                "tensor_parallel_size": tensor_parallel_size,
                "quantization": quantization,
                "disable_log_requests": disable_log_requests,
                "chat_template": chat_template,
                "tool_call_parser": tool_call_parser,
                "enable_auto_tool_choice": enable_auto_tool_choice,
                "load_format": load_format,
                "config_format": config_format,
                "tokenizer_mode": tokenizer_mode,
                "limit_mm_per_prompt": limit_mm_per_prompt,
                "max_num_batched_tokens": max_num_batched_tokens,
                "tokenizer": tokenizer,
                "dtype": dtype,
                "seed": seed,
                "revision": revision,
                "code_revision": code_revision,
                "rope_scaling": rope_scaling,
                "tokenizer_revision": tokenizer_revision,
                "quantization_param_path": quantization_param_path,
                "max_seq_len_to_capture": max_seq_len_to_capture,
                "disable_sliding_window": disable_sliding_window,
                "skip_tokenizer_init": skip_tokenizer_init,
                "served_model_name": served_model_name,
                "override_neuron_config": override_neuron_config,
                "mm_processor_kwargs": mm_processor_kwargs,
                "block_size": block_size,
                "gpu_memory_utilization": gpu_memory_utilization,
                "swap_space": swap_space,
                "cache_dtype": cache_dtype,
                "num_gpu_blocks_override": num_gpu_blocks_override,
                "enable_prefix_caching": enable_prefix_caching,
                "checkpoint_path": checkpoint_path,
                "num_shards": num_shards,
                "max_context_length": max_context_length,
                "response_role": response_role,
                "labels": labels,
            }
    
    model: MetaOapg.properties.model
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["model"]) -> MetaOapg.properties.model: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["max_model_len"]) -> MetaOapg.properties.max_model_len: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["max_num_seqs"]) -> MetaOapg.properties.max_num_seqs: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["enforce_eager"]) -> MetaOapg.properties.enforce_eager: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["trust_remote_code"]) -> MetaOapg.properties.trust_remote_code: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["pipeline_parallel_size"]) -> MetaOapg.properties.pipeline_parallel_size: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["tensor_parallel_size"]) -> MetaOapg.properties.tensor_parallel_size: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["quantization"]) -> MetaOapg.properties.quantization: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["disable_log_requests"]) -> MetaOapg.properties.disable_log_requests: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["chat_template"]) -> MetaOapg.properties.chat_template: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["tool_call_parser"]) -> MetaOapg.properties.tool_call_parser: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["enable_auto_tool_choice"]) -> MetaOapg.properties.enable_auto_tool_choice: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["load_format"]) -> MetaOapg.properties.load_format: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["config_format"]) -> MetaOapg.properties.config_format: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["tokenizer_mode"]) -> MetaOapg.properties.tokenizer_mode: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["limit_mm_per_prompt"]) -> MetaOapg.properties.limit_mm_per_prompt: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["max_num_batched_tokens"]) -> MetaOapg.properties.max_num_batched_tokens: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["tokenizer"]) -> MetaOapg.properties.tokenizer: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["dtype"]) -> MetaOapg.properties.dtype: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["seed"]) -> MetaOapg.properties.seed: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["revision"]) -> MetaOapg.properties.revision: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["code_revision"]) -> MetaOapg.properties.code_revision: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["rope_scaling"]) -> MetaOapg.properties.rope_scaling: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["tokenizer_revision"]) -> MetaOapg.properties.tokenizer_revision: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["quantization_param_path"]) -> MetaOapg.properties.quantization_param_path: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["max_seq_len_to_capture"]) -> MetaOapg.properties.max_seq_len_to_capture: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["disable_sliding_window"]) -> MetaOapg.properties.disable_sliding_window: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["skip_tokenizer_init"]) -> MetaOapg.properties.skip_tokenizer_init: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["served_model_name"]) -> MetaOapg.properties.served_model_name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["override_neuron_config"]) -> MetaOapg.properties.override_neuron_config: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["mm_processor_kwargs"]) -> MetaOapg.properties.mm_processor_kwargs: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["block_size"]) -> MetaOapg.properties.block_size: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["gpu_memory_utilization"]) -> MetaOapg.properties.gpu_memory_utilization: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["swap_space"]) -> MetaOapg.properties.swap_space: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["cache_dtype"]) -> MetaOapg.properties.cache_dtype: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["num_gpu_blocks_override"]) -> MetaOapg.properties.num_gpu_blocks_override: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["enable_prefix_caching"]) -> MetaOapg.properties.enable_prefix_caching: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["checkpoint_path"]) -> MetaOapg.properties.checkpoint_path: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["num_shards"]) -> MetaOapg.properties.num_shards: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["max_context_length"]) -> MetaOapg.properties.max_context_length: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["response_role"]) -> MetaOapg.properties.response_role: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["labels"]) -> MetaOapg.properties.labels: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["model", "max_model_len", "max_num_seqs", "enforce_eager", "trust_remote_code", "pipeline_parallel_size", "tensor_parallel_size", "quantization", "disable_log_requests", "chat_template", "tool_call_parser", "enable_auto_tool_choice", "load_format", "config_format", "tokenizer_mode", "limit_mm_per_prompt", "max_num_batched_tokens", "tokenizer", "dtype", "seed", "revision", "code_revision", "rope_scaling", "tokenizer_revision", "quantization_param_path", "max_seq_len_to_capture", "disable_sliding_window", "skip_tokenizer_init", "served_model_name", "override_neuron_config", "mm_processor_kwargs", "block_size", "gpu_memory_utilization", "swap_space", "cache_dtype", "num_gpu_blocks_override", "enable_prefix_caching", "checkpoint_path", "num_shards", "max_context_length", "response_role", "labels", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["model"]) -> MetaOapg.properties.model: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["max_model_len"]) -> typing.Union[MetaOapg.properties.max_model_len, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["max_num_seqs"]) -> typing.Union[MetaOapg.properties.max_num_seqs, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["enforce_eager"]) -> typing.Union[MetaOapg.properties.enforce_eager, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["trust_remote_code"]) -> typing.Union[MetaOapg.properties.trust_remote_code, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["pipeline_parallel_size"]) -> typing.Union[MetaOapg.properties.pipeline_parallel_size, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["tensor_parallel_size"]) -> typing.Union[MetaOapg.properties.tensor_parallel_size, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["quantization"]) -> typing.Union[MetaOapg.properties.quantization, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["disable_log_requests"]) -> typing.Union[MetaOapg.properties.disable_log_requests, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["chat_template"]) -> typing.Union[MetaOapg.properties.chat_template, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["tool_call_parser"]) -> typing.Union[MetaOapg.properties.tool_call_parser, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["enable_auto_tool_choice"]) -> typing.Union[MetaOapg.properties.enable_auto_tool_choice, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["load_format"]) -> typing.Union[MetaOapg.properties.load_format, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["config_format"]) -> typing.Union[MetaOapg.properties.config_format, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["tokenizer_mode"]) -> typing.Union[MetaOapg.properties.tokenizer_mode, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["limit_mm_per_prompt"]) -> typing.Union[MetaOapg.properties.limit_mm_per_prompt, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["max_num_batched_tokens"]) -> typing.Union[MetaOapg.properties.max_num_batched_tokens, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["tokenizer"]) -> typing.Union[MetaOapg.properties.tokenizer, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["dtype"]) -> typing.Union[MetaOapg.properties.dtype, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["seed"]) -> typing.Union[MetaOapg.properties.seed, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["revision"]) -> typing.Union[MetaOapg.properties.revision, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["code_revision"]) -> typing.Union[MetaOapg.properties.code_revision, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["rope_scaling"]) -> typing.Union[MetaOapg.properties.rope_scaling, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["tokenizer_revision"]) -> typing.Union[MetaOapg.properties.tokenizer_revision, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["quantization_param_path"]) -> typing.Union[MetaOapg.properties.quantization_param_path, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["max_seq_len_to_capture"]) -> typing.Union[MetaOapg.properties.max_seq_len_to_capture, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["disable_sliding_window"]) -> typing.Union[MetaOapg.properties.disable_sliding_window, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["skip_tokenizer_init"]) -> typing.Union[MetaOapg.properties.skip_tokenizer_init, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["served_model_name"]) -> typing.Union[MetaOapg.properties.served_model_name, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["override_neuron_config"]) -> typing.Union[MetaOapg.properties.override_neuron_config, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["mm_processor_kwargs"]) -> typing.Union[MetaOapg.properties.mm_processor_kwargs, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["block_size"]) -> typing.Union[MetaOapg.properties.block_size, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["gpu_memory_utilization"]) -> typing.Union[MetaOapg.properties.gpu_memory_utilization, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["swap_space"]) -> typing.Union[MetaOapg.properties.swap_space, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["cache_dtype"]) -> typing.Union[MetaOapg.properties.cache_dtype, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["num_gpu_blocks_override"]) -> typing.Union[MetaOapg.properties.num_gpu_blocks_override, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["enable_prefix_caching"]) -> typing.Union[MetaOapg.properties.enable_prefix_caching, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["checkpoint_path"]) -> typing.Union[MetaOapg.properties.checkpoint_path, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["num_shards"]) -> typing.Union[MetaOapg.properties.num_shards, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["max_context_length"]) -> typing.Union[MetaOapg.properties.max_context_length, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["response_role"]) -> typing.Union[MetaOapg.properties.response_role, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["labels"]) -> typing.Union[MetaOapg.properties.labels, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["model", "max_model_len", "max_num_seqs", "enforce_eager", "trust_remote_code", "pipeline_parallel_size", "tensor_parallel_size", "quantization", "disable_log_requests", "chat_template", "tool_call_parser", "enable_auto_tool_choice", "load_format", "config_format", "tokenizer_mode", "limit_mm_per_prompt", "max_num_batched_tokens", "tokenizer", "dtype", "seed", "revision", "code_revision", "rope_scaling", "tokenizer_revision", "quantization_param_path", "max_seq_len_to_capture", "disable_sliding_window", "skip_tokenizer_init", "served_model_name", "override_neuron_config", "mm_processor_kwargs", "block_size", "gpu_memory_utilization", "swap_space", "cache_dtype", "num_gpu_blocks_override", "enable_prefix_caching", "checkpoint_path", "num_shards", "max_context_length", "response_role", "labels", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        model: typing.Union[MetaOapg.properties.model, str, ],
        max_model_len: typing.Union[MetaOapg.properties.max_model_len, None, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        max_num_seqs: typing.Union[MetaOapg.properties.max_num_seqs, None, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        enforce_eager: typing.Union[MetaOapg.properties.enforce_eager, None, bool, schemas.Unset] = schemas.unset,
        trust_remote_code: typing.Union[MetaOapg.properties.trust_remote_code, None, bool, schemas.Unset] = schemas.unset,
        pipeline_parallel_size: typing.Union[MetaOapg.properties.pipeline_parallel_size, None, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        tensor_parallel_size: typing.Union[MetaOapg.properties.tensor_parallel_size, None, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        quantization: typing.Union[MetaOapg.properties.quantization, None, str, schemas.Unset] = schemas.unset,
        disable_log_requests: typing.Union[MetaOapg.properties.disable_log_requests, None, bool, schemas.Unset] = schemas.unset,
        chat_template: typing.Union[MetaOapg.properties.chat_template, None, str, schemas.Unset] = schemas.unset,
        tool_call_parser: typing.Union[MetaOapg.properties.tool_call_parser, None, str, schemas.Unset] = schemas.unset,
        enable_auto_tool_choice: typing.Union[MetaOapg.properties.enable_auto_tool_choice, None, bool, schemas.Unset] = schemas.unset,
        load_format: typing.Union[MetaOapg.properties.load_format, None, str, schemas.Unset] = schemas.unset,
        config_format: typing.Union[MetaOapg.properties.config_format, None, str, schemas.Unset] = schemas.unset,
        tokenizer_mode: typing.Union[MetaOapg.properties.tokenizer_mode, None, str, schemas.Unset] = schemas.unset,
        limit_mm_per_prompt: typing.Union[MetaOapg.properties.limit_mm_per_prompt, None, str, schemas.Unset] = schemas.unset,
        max_num_batched_tokens: typing.Union[MetaOapg.properties.max_num_batched_tokens, None, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        tokenizer: typing.Union[MetaOapg.properties.tokenizer, None, str, schemas.Unset] = schemas.unset,
        dtype: typing.Union[MetaOapg.properties.dtype, None, str, schemas.Unset] = schemas.unset,
        seed: typing.Union[MetaOapg.properties.seed, None, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        revision: typing.Union[MetaOapg.properties.revision, None, str, schemas.Unset] = schemas.unset,
        code_revision: typing.Union[MetaOapg.properties.code_revision, None, str, schemas.Unset] = schemas.unset,
        rope_scaling: typing.Union[MetaOapg.properties.rope_scaling, dict, frozendict.frozendict, None, schemas.Unset] = schemas.unset,
        tokenizer_revision: typing.Union[MetaOapg.properties.tokenizer_revision, None, str, schemas.Unset] = schemas.unset,
        quantization_param_path: typing.Union[MetaOapg.properties.quantization_param_path, None, str, schemas.Unset] = schemas.unset,
        max_seq_len_to_capture: typing.Union[MetaOapg.properties.max_seq_len_to_capture, None, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        disable_sliding_window: typing.Union[MetaOapg.properties.disable_sliding_window, None, bool, schemas.Unset] = schemas.unset,
        skip_tokenizer_init: typing.Union[MetaOapg.properties.skip_tokenizer_init, None, bool, schemas.Unset] = schemas.unset,
        served_model_name: typing.Union[MetaOapg.properties.served_model_name, None, str, schemas.Unset] = schemas.unset,
        override_neuron_config: typing.Union[MetaOapg.properties.override_neuron_config, dict, frozendict.frozendict, None, schemas.Unset] = schemas.unset,
        mm_processor_kwargs: typing.Union[MetaOapg.properties.mm_processor_kwargs, dict, frozendict.frozendict, None, schemas.Unset] = schemas.unset,
        block_size: typing.Union[MetaOapg.properties.block_size, None, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        gpu_memory_utilization: typing.Union[MetaOapg.properties.gpu_memory_utilization, None, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        swap_space: typing.Union[MetaOapg.properties.swap_space, None, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        cache_dtype: typing.Union[MetaOapg.properties.cache_dtype, None, str, schemas.Unset] = schemas.unset,
        num_gpu_blocks_override: typing.Union[MetaOapg.properties.num_gpu_blocks_override, None, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        enable_prefix_caching: typing.Union[MetaOapg.properties.enable_prefix_caching, None, bool, schemas.Unset] = schemas.unset,
        checkpoint_path: typing.Union[MetaOapg.properties.checkpoint_path, None, str, schemas.Unset] = schemas.unset,
        num_shards: typing.Union[MetaOapg.properties.num_shards, None, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        max_context_length: typing.Union[MetaOapg.properties.max_context_length, None, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        response_role: typing.Union[MetaOapg.properties.response_role, None, str, schemas.Unset] = schemas.unset,
        labels: typing.Union[MetaOapg.properties.labels, dict, frozendict.frozendict, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'CreateBatchCompletionsV1ModelConfig':
        return super().__new__(
            cls,
            *_args,
            model=model,
            max_model_len=max_model_len,
            max_num_seqs=max_num_seqs,
            enforce_eager=enforce_eager,
            trust_remote_code=trust_remote_code,
            pipeline_parallel_size=pipeline_parallel_size,
            tensor_parallel_size=tensor_parallel_size,
            quantization=quantization,
            disable_log_requests=disable_log_requests,
            chat_template=chat_template,
            tool_call_parser=tool_call_parser,
            enable_auto_tool_choice=enable_auto_tool_choice,
            load_format=load_format,
            config_format=config_format,
            tokenizer_mode=tokenizer_mode,
            limit_mm_per_prompt=limit_mm_per_prompt,
            max_num_batched_tokens=max_num_batched_tokens,
            tokenizer=tokenizer,
            dtype=dtype,
            seed=seed,
            revision=revision,
            code_revision=code_revision,
            rope_scaling=rope_scaling,
            tokenizer_revision=tokenizer_revision,
            quantization_param_path=quantization_param_path,
            max_seq_len_to_capture=max_seq_len_to_capture,
            disable_sliding_window=disable_sliding_window,
            skip_tokenizer_init=skip_tokenizer_init,
            served_model_name=served_model_name,
            override_neuron_config=override_neuron_config,
            mm_processor_kwargs=mm_processor_kwargs,
            block_size=block_size,
            gpu_memory_utilization=gpu_memory_utilization,
            swap_space=swap_space,
            cache_dtype=cache_dtype,
            num_gpu_blocks_override=num_gpu_blocks_override,
            enable_prefix_caching=enable_prefix_caching,
            checkpoint_path=checkpoint_path,
            num_shards=num_shards,
            max_context_length=max_context_length,
            response_role=response_role,
            labels=labels,
            _configuration=_configuration,
            **kwargs,
        )
