# coding: utf-8

"""
    launch

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from launch.api_client import schemas  # noqa: F401


class StreamingEnhancedRunnableImageFlavor(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    For deployments that expose a streaming route in a container.
    """


    class MetaOapg:
        required = {
            "flavor",
            "protocol",
            "tag",
            "repository",
            "streaming_command",
        }
        
        class properties:
            repository = schemas.StrSchema
            tag = schemas.StrSchema
            
            
            class protocol(
                schemas.EnumBase,
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    enum_value_to_name = {
                        "http": "HTTP",
                    }
                
                @schemas.classproperty
                def HTTP(cls):
                    return cls("http")
            
            
            class flavor(
                schemas.EnumBase,
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    enum_value_to_name = {
                        "streaming_enhanced_runnable_image": "STREAMING_ENHANCED_RUNNABLE_IMAGE",
                    }
                
                @schemas.classproperty
                def STREAMING_ENHANCED_RUNNABLE_IMAGE(cls):
                    return cls("streaming_enhanced_runnable_image")
            
            
            class streaming_command(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    items = schemas.StrSchema
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple[typing.Union[MetaOapg.items, str, ]], typing.List[typing.Union[MetaOapg.items, str, ]]],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'streaming_command':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> MetaOapg.items:
                    return super().__getitem__(i)
            
            
            class command(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    items = schemas.StrSchema
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple[typing.Union[MetaOapg.items, str, ]], typing.List[typing.Union[MetaOapg.items, str, ]]],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'command':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> MetaOapg.items:
                    return super().__getitem__(i)
            predict_route = schemas.StrSchema
            healthcheck_route = schemas.StrSchema
            
            
            class env(
                schemas.DictBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneFrozenDictMixin
            ):
            
            
                class MetaOapg:
                    additional_properties = schemas.StrSchema
            
                
                def __getitem__(self, name: typing.Union[str, ]) -> MetaOapg.additional_properties:
                    # dict_instance[name] accessor
                    return super().__getitem__(name)
                
                def get_item_oapg(self, name: typing.Union[str, ]) -> MetaOapg.additional_properties:
                    return super().get_item_oapg(name)
            
                def __new__(
                    cls,
                    *_args: typing.Union[dict, frozendict.frozendict, None, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                    **kwargs: typing.Union[MetaOapg.additional_properties, str, ],
                ) -> 'env':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                        **kwargs,
                    )
            readiness_initial_delay_seconds = schemas.IntSchema
            
            
            class extra_routes(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    items = schemas.StrSchema
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple[typing.Union[MetaOapg.items, str, ]], typing.List[typing.Union[MetaOapg.items, str, ]]],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'extra_routes':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> MetaOapg.items:
                    return super().__getitem__(i)
            
            
            class routes(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    items = schemas.StrSchema
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple[typing.Union[MetaOapg.items, str, ]], typing.List[typing.Union[MetaOapg.items, str, ]]],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'routes':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> MetaOapg.items:
                    return super().__getitem__(i)
            
            
            class forwarder_type(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'forwarder_type':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class worker_command(
                schemas.ListBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneTupleMixin
            ):
            
            
                class MetaOapg:
                    items = schemas.StrSchema
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[list, tuple, None, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'worker_command':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class worker_env(
                schemas.DictBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneFrozenDictMixin
            ):
            
            
                class MetaOapg:
                    additional_properties = schemas.StrSchema
            
                
                def __getitem__(self, name: typing.Union[str, ]) -> MetaOapg.additional_properties:
                    # dict_instance[name] accessor
                    return super().__getitem__(name)
                
                def get_item_oapg(self, name: typing.Union[str, ]) -> MetaOapg.additional_properties:
                    return super().get_item_oapg(name)
            
                def __new__(
                    cls,
                    *_args: typing.Union[dict, frozendict.frozendict, None, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                    **kwargs: typing.Union[MetaOapg.additional_properties, str, ],
                ) -> 'worker_env':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                        **kwargs,
                    )
            streaming_predict_route = schemas.StrSchema
            __annotations__ = {
                "repository": repository,
                "tag": tag,
                "protocol": protocol,
                "flavor": flavor,
                "streaming_command": streaming_command,
                "command": command,
                "predict_route": predict_route,
                "healthcheck_route": healthcheck_route,
                "env": env,
                "readiness_initial_delay_seconds": readiness_initial_delay_seconds,
                "extra_routes": extra_routes,
                "routes": routes,
                "forwarder_type": forwarder_type,
                "worker_command": worker_command,
                "worker_env": worker_env,
                "streaming_predict_route": streaming_predict_route,
            }
    
    flavor: MetaOapg.properties.flavor
    protocol: MetaOapg.properties.protocol
    tag: MetaOapg.properties.tag
    repository: MetaOapg.properties.repository
    streaming_command: MetaOapg.properties.streaming_command
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["repository"]) -> MetaOapg.properties.repository: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["tag"]) -> MetaOapg.properties.tag: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["protocol"]) -> MetaOapg.properties.protocol: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["flavor"]) -> MetaOapg.properties.flavor: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["streaming_command"]) -> MetaOapg.properties.streaming_command: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["command"]) -> MetaOapg.properties.command: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["predict_route"]) -> MetaOapg.properties.predict_route: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["healthcheck_route"]) -> MetaOapg.properties.healthcheck_route: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["env"]) -> MetaOapg.properties.env: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["readiness_initial_delay_seconds"]) -> MetaOapg.properties.readiness_initial_delay_seconds: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["extra_routes"]) -> MetaOapg.properties.extra_routes: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["routes"]) -> MetaOapg.properties.routes: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["forwarder_type"]) -> MetaOapg.properties.forwarder_type: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["worker_command"]) -> MetaOapg.properties.worker_command: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["worker_env"]) -> MetaOapg.properties.worker_env: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["streaming_predict_route"]) -> MetaOapg.properties.streaming_predict_route: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["repository", "tag", "protocol", "flavor", "streaming_command", "command", "predict_route", "healthcheck_route", "env", "readiness_initial_delay_seconds", "extra_routes", "routes", "forwarder_type", "worker_command", "worker_env", "streaming_predict_route", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["repository"]) -> MetaOapg.properties.repository: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["tag"]) -> MetaOapg.properties.tag: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["protocol"]) -> MetaOapg.properties.protocol: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["flavor"]) -> MetaOapg.properties.flavor: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["streaming_command"]) -> MetaOapg.properties.streaming_command: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["command"]) -> typing.Union[MetaOapg.properties.command, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["predict_route"]) -> typing.Union[MetaOapg.properties.predict_route, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["healthcheck_route"]) -> typing.Union[MetaOapg.properties.healthcheck_route, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["env"]) -> typing.Union[MetaOapg.properties.env, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["readiness_initial_delay_seconds"]) -> typing.Union[MetaOapg.properties.readiness_initial_delay_seconds, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["extra_routes"]) -> typing.Union[MetaOapg.properties.extra_routes, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["routes"]) -> typing.Union[MetaOapg.properties.routes, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["forwarder_type"]) -> typing.Union[MetaOapg.properties.forwarder_type, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["worker_command"]) -> typing.Union[MetaOapg.properties.worker_command, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["worker_env"]) -> typing.Union[MetaOapg.properties.worker_env, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["streaming_predict_route"]) -> typing.Union[MetaOapg.properties.streaming_predict_route, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["repository", "tag", "protocol", "flavor", "streaming_command", "command", "predict_route", "healthcheck_route", "env", "readiness_initial_delay_seconds", "extra_routes", "routes", "forwarder_type", "worker_command", "worker_env", "streaming_predict_route", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        flavor: typing.Union[MetaOapg.properties.flavor, str, ],
        protocol: typing.Union[MetaOapg.properties.protocol, str, ],
        tag: typing.Union[MetaOapg.properties.tag, str, ],
        repository: typing.Union[MetaOapg.properties.repository, str, ],
        streaming_command: typing.Union[MetaOapg.properties.streaming_command, list, tuple, ],
        command: typing.Union[MetaOapg.properties.command, list, tuple, schemas.Unset] = schemas.unset,
        predict_route: typing.Union[MetaOapg.properties.predict_route, str, schemas.Unset] = schemas.unset,
        healthcheck_route: typing.Union[MetaOapg.properties.healthcheck_route, str, schemas.Unset] = schemas.unset,
        env: typing.Union[MetaOapg.properties.env, dict, frozendict.frozendict, None, schemas.Unset] = schemas.unset,
        readiness_initial_delay_seconds: typing.Union[MetaOapg.properties.readiness_initial_delay_seconds, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        extra_routes: typing.Union[MetaOapg.properties.extra_routes, list, tuple, schemas.Unset] = schemas.unset,
        routes: typing.Union[MetaOapg.properties.routes, list, tuple, schemas.Unset] = schemas.unset,
        forwarder_type: typing.Union[MetaOapg.properties.forwarder_type, None, str, schemas.Unset] = schemas.unset,
        worker_command: typing.Union[MetaOapg.properties.worker_command, list, tuple, None, schemas.Unset] = schemas.unset,
        worker_env: typing.Union[MetaOapg.properties.worker_env, dict, frozendict.frozendict, None, schemas.Unset] = schemas.unset,
        streaming_predict_route: typing.Union[MetaOapg.properties.streaming_predict_route, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'StreamingEnhancedRunnableImageFlavor':
        return super().__new__(
            cls,
            *_args,
            flavor=flavor,
            protocol=protocol,
            tag=tag,
            repository=repository,
            streaming_command=streaming_command,
            command=command,
            predict_route=predict_route,
            healthcheck_route=healthcheck_route,
            env=env,
            readiness_initial_delay_seconds=readiness_initial_delay_seconds,
            extra_routes=extra_routes,
            routes=routes,
            forwarder_type=forwarder_type,
            worker_command=worker_command,
            worker_env=worker_env,
            streaming_predict_route=streaming_predict_route,
            _configuration=_configuration,
            **kwargs,
        )
