# coding: utf-8

"""
    launch

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from launch.api_client import schemas  # noqa: F401


class UpdateVLLMModelEndpointRequest(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
        
            @staticmethod
            def quantize() -> typing.Type['Quantization']:
                return Quantization
            
            
            class checkpoint_path(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'checkpoint_path':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class post_inference_hooks(
                schemas.ListBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneTupleMixin
            ):
            
            
                class MetaOapg:
                    items = schemas.StrSchema
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[list, tuple, None, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'post_inference_hooks':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class cpus(
                schemas.ComposedSchema,
            ):
            
            
                class MetaOapg:
                    any_of_0 = schemas.StrSchema
                    any_of_1 = schemas.IntSchema
                    any_of_2 = schemas.NumberSchema
                    
                    @classmethod
                    @functools.lru_cache()
                    def any_of(cls):
                        # we need this here to make our import statements work
                        # we must store _composed_schemas in here so the code is only run
                        # when we invoke this method. If we kept this at the class
                        # level we would get an error because the class level
                        # code would be run when this module is imported, and these composed
                        # classes don't exist yet because their module has not finished
                        # loading
                        return [
                            cls.any_of_0,
                            cls.any_of_1,
                            cls.any_of_2,
                        ]
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                    **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
                ) -> 'cpus':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                        **kwargs,
                    )
            
            
            class gpus(
                schemas.IntBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneDecimalMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, decimal.Decimal, int, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'gpus':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class memory(
                schemas.ComposedSchema,
            ):
            
            
                class MetaOapg:
                    any_of_0 = schemas.StrSchema
                    any_of_1 = schemas.IntSchema
                    any_of_2 = schemas.NumberSchema
                    
                    @classmethod
                    @functools.lru_cache()
                    def any_of(cls):
                        # we need this here to make our import statements work
                        # we must store _composed_schemas in here so the code is only run
                        # when we invoke this method. If we kept this at the class
                        # level we would get an error because the class level
                        # code would be run when this module is imported, and these composed
                        # classes don't exist yet because their module has not finished
                        # loading
                        return [
                            cls.any_of_0,
                            cls.any_of_1,
                            cls.any_of_2,
                        ]
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                    **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
                ) -> 'memory':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                        **kwargs,
                    )
        
            @staticmethod
            def gpu_type() -> typing.Type['GpuType']:
                return GpuType
            
            
            class storage(
                schemas.ComposedSchema,
            ):
            
            
                class MetaOapg:
                    any_of_0 = schemas.StrSchema
                    any_of_1 = schemas.IntSchema
                    any_of_2 = schemas.NumberSchema
                    
                    @classmethod
                    @functools.lru_cache()
                    def any_of(cls):
                        # we need this here to make our import statements work
                        # we must store _composed_schemas in here so the code is only run
                        # when we invoke this method. If we kept this at the class
                        # level we would get an error because the class level
                        # code would be run when this module is imported, and these composed
                        # classes don't exist yet because their module has not finished
                        # loading
                        return [
                            cls.any_of_0,
                            cls.any_of_1,
                            cls.any_of_2,
                        ]
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                    **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
                ) -> 'storage':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                        **kwargs,
                    )
            
            
            class nodes_per_worker(
                schemas.IntBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneDecimalMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, decimal.Decimal, int, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'nodes_per_worker':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class optimize_costs(
                schemas.BoolBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneBoolMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, bool, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'optimize_costs':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class prewarm(
                schemas.BoolBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneBoolMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, bool, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'prewarm':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class high_priority(
                schemas.BoolBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneBoolMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, bool, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'high_priority':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class billing_tags(
                schemas.DictBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneFrozenDictMixin
            ):
            
            
                class MetaOapg:
                    additional_properties = schemas.AnyTypeSchema
            
                
                def __getitem__(self, name: typing.Union[str, ]) -> MetaOapg.additional_properties:
                    # dict_instance[name] accessor
                    return super().__getitem__(name)
                
                def get_item_oapg(self, name: typing.Union[str, ]) -> MetaOapg.additional_properties:
                    return super().get_item_oapg(name)
            
                def __new__(
                    cls,
                    *_args: typing.Union[dict, frozendict.frozendict, None, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                    **kwargs: typing.Union[MetaOapg.additional_properties, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
                ) -> 'billing_tags':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                        **kwargs,
                    )
            
            
            class default_callback_url(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'default_callback_url':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
        
            @staticmethod
            def default_callback_auth() -> typing.Type['CallbackAuth']:
                return CallbackAuth
            
            
            class public_inference(
                schemas.BoolBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneBoolMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, bool, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'public_inference':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class chat_template_override(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'chat_template_override':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class enable_startup_metrics(
                schemas.BoolBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneBoolMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, bool, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'enable_startup_metrics':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class model_name(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'model_name':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
        
            @staticmethod
            def source() -> typing.Type['LLMSource']:
                return LLMSource
            
            
            class inference_framework(
                schemas.EnumBase,
                schemas.StrSchema
            ):
                
                @schemas.classproperty
                def VLLM(cls):
                    return cls("vllm")
            
            
            class inference_framework_image_tag(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'inference_framework_image_tag':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class num_shards(
                schemas.IntBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneDecimalMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, decimal.Decimal, int, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'num_shards':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class metadata(
                schemas.DictBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneFrozenDictMixin
            ):
            
            
                class MetaOapg:
                    additional_properties = schemas.AnyTypeSchema
            
                
                def __getitem__(self, name: typing.Union[str, ]) -> MetaOapg.additional_properties:
                    # dict_instance[name] accessor
                    return super().__getitem__(name)
                
                def get_item_oapg(self, name: typing.Union[str, ]) -> MetaOapg.additional_properties:
                    return super().get_item_oapg(name)
            
                def __new__(
                    cls,
                    *_args: typing.Union[dict, frozendict.frozendict, None, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                    **kwargs: typing.Union[MetaOapg.additional_properties, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
                ) -> 'metadata':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                        **kwargs,
                    )
            
            
            class force_bundle_recreation(
                schemas.BoolBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneBoolMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, bool, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'force_bundle_recreation':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class min_workers(
                schemas.IntBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneDecimalMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, decimal.Decimal, int, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'min_workers':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class max_workers(
                schemas.IntBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneDecimalMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, decimal.Decimal, int, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'max_workers':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class per_worker(
                schemas.IntBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneDecimalMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, decimal.Decimal, int, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'per_worker':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class labels(
                schemas.DictBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneFrozenDictMixin
            ):
            
            
                class MetaOapg:
                    additional_properties = schemas.StrSchema
            
                
                def __getitem__(self, name: typing.Union[str, ]) -> MetaOapg.additional_properties:
                    # dict_instance[name] accessor
                    return super().__getitem__(name)
                
                def get_item_oapg(self, name: typing.Union[str, ]) -> MetaOapg.additional_properties:
                    return super().get_item_oapg(name)
            
                def __new__(
                    cls,
                    *_args: typing.Union[dict, frozendict.frozendict, None, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                    **kwargs: typing.Union[MetaOapg.additional_properties, str, ],
                ) -> 'labels':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                        **kwargs,
                    )
            
            
            class max_gpu_memory_utilization(
                schemas.NumberBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneDecimalMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, decimal.Decimal, int, float, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'max_gpu_memory_utilization':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class attention_backend(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'attention_backend':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class max_model_len(
                schemas.IntBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneDecimalMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, decimal.Decimal, int, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'max_model_len':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class max_num_seqs(
                schemas.IntBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneDecimalMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, decimal.Decimal, int, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'max_num_seqs':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class enforce_eager(
                schemas.BoolBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneBoolMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, bool, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'enforce_eager':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class trust_remote_code(
                schemas.BoolBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneBoolMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, bool, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'trust_remote_code':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class pipeline_parallel_size(
                schemas.IntBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneDecimalMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, decimal.Decimal, int, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'pipeline_parallel_size':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class tensor_parallel_size(
                schemas.IntBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneDecimalMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, decimal.Decimal, int, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'tensor_parallel_size':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class quantization(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'quantization':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class disable_log_requests(
                schemas.BoolBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneBoolMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, bool, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'disable_log_requests':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class chat_template(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'chat_template':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class tool_call_parser(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'tool_call_parser':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class enable_auto_tool_choice(
                schemas.BoolBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneBoolMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, bool, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'enable_auto_tool_choice':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class load_format(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'load_format':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class config_format(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'config_format':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class tokenizer_mode(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'tokenizer_mode':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class limit_mm_per_prompt(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'limit_mm_per_prompt':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class max_num_batched_tokens(
                schemas.IntBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneDecimalMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, decimal.Decimal, int, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'max_num_batched_tokens':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class tokenizer(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'tokenizer':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class dtype(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'dtype':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class seed(
                schemas.IntBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneDecimalMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, decimal.Decimal, int, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'seed':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class revision(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'revision':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class code_revision(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'code_revision':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class rope_scaling(
                schemas.DictBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneFrozenDictMixin
            ):
            
            
                class MetaOapg:
                    additional_properties = schemas.AnyTypeSchema
            
                
                def __getitem__(self, name: typing.Union[str, ]) -> MetaOapg.additional_properties:
                    # dict_instance[name] accessor
                    return super().__getitem__(name)
                
                def get_item_oapg(self, name: typing.Union[str, ]) -> MetaOapg.additional_properties:
                    return super().get_item_oapg(name)
            
                def __new__(
                    cls,
                    *_args: typing.Union[dict, frozendict.frozendict, None, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                    **kwargs: typing.Union[MetaOapg.additional_properties, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
                ) -> 'rope_scaling':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                        **kwargs,
                    )
            
            
            class tokenizer_revision(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'tokenizer_revision':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class quantization_param_path(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'quantization_param_path':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class max_seq_len_to_capture(
                schemas.IntBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneDecimalMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, decimal.Decimal, int, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'max_seq_len_to_capture':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class disable_sliding_window(
                schemas.BoolBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneBoolMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, bool, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'disable_sliding_window':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class skip_tokenizer_init(
                schemas.BoolBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneBoolMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, bool, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'skip_tokenizer_init':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class served_model_name(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'served_model_name':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class override_neuron_config(
                schemas.DictBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneFrozenDictMixin
            ):
            
            
                class MetaOapg:
                    additional_properties = schemas.AnyTypeSchema
            
                
                def __getitem__(self, name: typing.Union[str, ]) -> MetaOapg.additional_properties:
                    # dict_instance[name] accessor
                    return super().__getitem__(name)
                
                def get_item_oapg(self, name: typing.Union[str, ]) -> MetaOapg.additional_properties:
                    return super().get_item_oapg(name)
            
                def __new__(
                    cls,
                    *_args: typing.Union[dict, frozendict.frozendict, None, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                    **kwargs: typing.Union[MetaOapg.additional_properties, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
                ) -> 'override_neuron_config':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                        **kwargs,
                    )
            
            
            class mm_processor_kwargs(
                schemas.DictBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneFrozenDictMixin
            ):
            
            
                class MetaOapg:
                    additional_properties = schemas.AnyTypeSchema
            
                
                def __getitem__(self, name: typing.Union[str, ]) -> MetaOapg.additional_properties:
                    # dict_instance[name] accessor
                    return super().__getitem__(name)
                
                def get_item_oapg(self, name: typing.Union[str, ]) -> MetaOapg.additional_properties:
                    return super().get_item_oapg(name)
            
                def __new__(
                    cls,
                    *_args: typing.Union[dict, frozendict.frozendict, None, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                    **kwargs: typing.Union[MetaOapg.additional_properties, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
                ) -> 'mm_processor_kwargs':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                        **kwargs,
                    )
            
            
            class block_size(
                schemas.IntBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneDecimalMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, decimal.Decimal, int, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'block_size':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class gpu_memory_utilization(
                schemas.NumberBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneDecimalMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, decimal.Decimal, int, float, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'gpu_memory_utilization':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class swap_space(
                schemas.NumberBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneDecimalMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, decimal.Decimal, int, float, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'swap_space':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class cache_dtype(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'cache_dtype':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class num_gpu_blocks_override(
                schemas.IntBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneDecimalMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, decimal.Decimal, int, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'num_gpu_blocks_override':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class enable_prefix_caching(
                schemas.BoolBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneBoolMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, bool, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'enable_prefix_caching':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            __annotations__ = {
                "quantize": quantize,
                "checkpoint_path": checkpoint_path,
                "post_inference_hooks": post_inference_hooks,
                "cpus": cpus,
                "gpus": gpus,
                "memory": memory,
                "gpu_type": gpu_type,
                "storage": storage,
                "nodes_per_worker": nodes_per_worker,
                "optimize_costs": optimize_costs,
                "prewarm": prewarm,
                "high_priority": high_priority,
                "billing_tags": billing_tags,
                "default_callback_url": default_callback_url,
                "default_callback_auth": default_callback_auth,
                "public_inference": public_inference,
                "chat_template_override": chat_template_override,
                "enable_startup_metrics": enable_startup_metrics,
                "model_name": model_name,
                "source": source,
                "inference_framework": inference_framework,
                "inference_framework_image_tag": inference_framework_image_tag,
                "num_shards": num_shards,
                "metadata": metadata,
                "force_bundle_recreation": force_bundle_recreation,
                "min_workers": min_workers,
                "max_workers": max_workers,
                "per_worker": per_worker,
                "labels": labels,
                "max_gpu_memory_utilization": max_gpu_memory_utilization,
                "attention_backend": attention_backend,
                "max_model_len": max_model_len,
                "max_num_seqs": max_num_seqs,
                "enforce_eager": enforce_eager,
                "trust_remote_code": trust_remote_code,
                "pipeline_parallel_size": pipeline_parallel_size,
                "tensor_parallel_size": tensor_parallel_size,
                "quantization": quantization,
                "disable_log_requests": disable_log_requests,
                "chat_template": chat_template,
                "tool_call_parser": tool_call_parser,
                "enable_auto_tool_choice": enable_auto_tool_choice,
                "load_format": load_format,
                "config_format": config_format,
                "tokenizer_mode": tokenizer_mode,
                "limit_mm_per_prompt": limit_mm_per_prompt,
                "max_num_batched_tokens": max_num_batched_tokens,
                "tokenizer": tokenizer,
                "dtype": dtype,
                "seed": seed,
                "revision": revision,
                "code_revision": code_revision,
                "rope_scaling": rope_scaling,
                "tokenizer_revision": tokenizer_revision,
                "quantization_param_path": quantization_param_path,
                "max_seq_len_to_capture": max_seq_len_to_capture,
                "disable_sliding_window": disable_sliding_window,
                "skip_tokenizer_init": skip_tokenizer_init,
                "served_model_name": served_model_name,
                "override_neuron_config": override_neuron_config,
                "mm_processor_kwargs": mm_processor_kwargs,
                "block_size": block_size,
                "gpu_memory_utilization": gpu_memory_utilization,
                "swap_space": swap_space,
                "cache_dtype": cache_dtype,
                "num_gpu_blocks_override": num_gpu_blocks_override,
                "enable_prefix_caching": enable_prefix_caching,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["quantize"]) -> 'Quantization': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["checkpoint_path"]) -> MetaOapg.properties.checkpoint_path: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["post_inference_hooks"]) -> MetaOapg.properties.post_inference_hooks: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["cpus"]) -> MetaOapg.properties.cpus: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["gpus"]) -> MetaOapg.properties.gpus: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["memory"]) -> MetaOapg.properties.memory: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["gpu_type"]) -> 'GpuType': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["storage"]) -> MetaOapg.properties.storage: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["nodes_per_worker"]) -> MetaOapg.properties.nodes_per_worker: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["optimize_costs"]) -> MetaOapg.properties.optimize_costs: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["prewarm"]) -> MetaOapg.properties.prewarm: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["high_priority"]) -> MetaOapg.properties.high_priority: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["billing_tags"]) -> MetaOapg.properties.billing_tags: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["default_callback_url"]) -> MetaOapg.properties.default_callback_url: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["default_callback_auth"]) -> 'CallbackAuth': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["public_inference"]) -> MetaOapg.properties.public_inference: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["chat_template_override"]) -> MetaOapg.properties.chat_template_override: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["enable_startup_metrics"]) -> MetaOapg.properties.enable_startup_metrics: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["model_name"]) -> MetaOapg.properties.model_name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["source"]) -> 'LLMSource': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["inference_framework"]) -> MetaOapg.properties.inference_framework: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["inference_framework_image_tag"]) -> MetaOapg.properties.inference_framework_image_tag: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["num_shards"]) -> MetaOapg.properties.num_shards: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["metadata"]) -> MetaOapg.properties.metadata: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["force_bundle_recreation"]) -> MetaOapg.properties.force_bundle_recreation: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["min_workers"]) -> MetaOapg.properties.min_workers: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["max_workers"]) -> MetaOapg.properties.max_workers: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["per_worker"]) -> MetaOapg.properties.per_worker: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["labels"]) -> MetaOapg.properties.labels: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["max_gpu_memory_utilization"]) -> MetaOapg.properties.max_gpu_memory_utilization: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["attention_backend"]) -> MetaOapg.properties.attention_backend: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["max_model_len"]) -> MetaOapg.properties.max_model_len: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["max_num_seqs"]) -> MetaOapg.properties.max_num_seqs: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["enforce_eager"]) -> MetaOapg.properties.enforce_eager: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["trust_remote_code"]) -> MetaOapg.properties.trust_remote_code: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["pipeline_parallel_size"]) -> MetaOapg.properties.pipeline_parallel_size: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["tensor_parallel_size"]) -> MetaOapg.properties.tensor_parallel_size: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["quantization"]) -> MetaOapg.properties.quantization: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["disable_log_requests"]) -> MetaOapg.properties.disable_log_requests: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["chat_template"]) -> MetaOapg.properties.chat_template: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["tool_call_parser"]) -> MetaOapg.properties.tool_call_parser: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["enable_auto_tool_choice"]) -> MetaOapg.properties.enable_auto_tool_choice: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["load_format"]) -> MetaOapg.properties.load_format: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["config_format"]) -> MetaOapg.properties.config_format: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["tokenizer_mode"]) -> MetaOapg.properties.tokenizer_mode: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["limit_mm_per_prompt"]) -> MetaOapg.properties.limit_mm_per_prompt: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["max_num_batched_tokens"]) -> MetaOapg.properties.max_num_batched_tokens: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["tokenizer"]) -> MetaOapg.properties.tokenizer: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["dtype"]) -> MetaOapg.properties.dtype: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["seed"]) -> MetaOapg.properties.seed: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["revision"]) -> MetaOapg.properties.revision: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["code_revision"]) -> MetaOapg.properties.code_revision: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["rope_scaling"]) -> MetaOapg.properties.rope_scaling: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["tokenizer_revision"]) -> MetaOapg.properties.tokenizer_revision: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["quantization_param_path"]) -> MetaOapg.properties.quantization_param_path: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["max_seq_len_to_capture"]) -> MetaOapg.properties.max_seq_len_to_capture: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["disable_sliding_window"]) -> MetaOapg.properties.disable_sliding_window: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["skip_tokenizer_init"]) -> MetaOapg.properties.skip_tokenizer_init: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["served_model_name"]) -> MetaOapg.properties.served_model_name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["override_neuron_config"]) -> MetaOapg.properties.override_neuron_config: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["mm_processor_kwargs"]) -> MetaOapg.properties.mm_processor_kwargs: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["block_size"]) -> MetaOapg.properties.block_size: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["gpu_memory_utilization"]) -> MetaOapg.properties.gpu_memory_utilization: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["swap_space"]) -> MetaOapg.properties.swap_space: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["cache_dtype"]) -> MetaOapg.properties.cache_dtype: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["num_gpu_blocks_override"]) -> MetaOapg.properties.num_gpu_blocks_override: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["enable_prefix_caching"]) -> MetaOapg.properties.enable_prefix_caching: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["quantize", "checkpoint_path", "post_inference_hooks", "cpus", "gpus", "memory", "gpu_type", "storage", "nodes_per_worker", "optimize_costs", "prewarm", "high_priority", "billing_tags", "default_callback_url", "default_callback_auth", "public_inference", "chat_template_override", "enable_startup_metrics", "model_name", "source", "inference_framework", "inference_framework_image_tag", "num_shards", "metadata", "force_bundle_recreation", "min_workers", "max_workers", "per_worker", "labels", "max_gpu_memory_utilization", "attention_backend", "max_model_len", "max_num_seqs", "enforce_eager", "trust_remote_code", "pipeline_parallel_size", "tensor_parallel_size", "quantization", "disable_log_requests", "chat_template", "tool_call_parser", "enable_auto_tool_choice", "load_format", "config_format", "tokenizer_mode", "limit_mm_per_prompt", "max_num_batched_tokens", "tokenizer", "dtype", "seed", "revision", "code_revision", "rope_scaling", "tokenizer_revision", "quantization_param_path", "max_seq_len_to_capture", "disable_sliding_window", "skip_tokenizer_init", "served_model_name", "override_neuron_config", "mm_processor_kwargs", "block_size", "gpu_memory_utilization", "swap_space", "cache_dtype", "num_gpu_blocks_override", "enable_prefix_caching", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["quantize"]) -> typing.Union['Quantization', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["checkpoint_path"]) -> typing.Union[MetaOapg.properties.checkpoint_path, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["post_inference_hooks"]) -> typing.Union[MetaOapg.properties.post_inference_hooks, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["cpus"]) -> typing.Union[MetaOapg.properties.cpus, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["gpus"]) -> typing.Union[MetaOapg.properties.gpus, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["memory"]) -> typing.Union[MetaOapg.properties.memory, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["gpu_type"]) -> typing.Union['GpuType', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["storage"]) -> typing.Union[MetaOapg.properties.storage, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["nodes_per_worker"]) -> typing.Union[MetaOapg.properties.nodes_per_worker, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["optimize_costs"]) -> typing.Union[MetaOapg.properties.optimize_costs, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["prewarm"]) -> typing.Union[MetaOapg.properties.prewarm, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["high_priority"]) -> typing.Union[MetaOapg.properties.high_priority, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["billing_tags"]) -> typing.Union[MetaOapg.properties.billing_tags, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["default_callback_url"]) -> typing.Union[MetaOapg.properties.default_callback_url, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["default_callback_auth"]) -> typing.Union['CallbackAuth', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["public_inference"]) -> typing.Union[MetaOapg.properties.public_inference, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["chat_template_override"]) -> typing.Union[MetaOapg.properties.chat_template_override, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["enable_startup_metrics"]) -> typing.Union[MetaOapg.properties.enable_startup_metrics, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["model_name"]) -> typing.Union[MetaOapg.properties.model_name, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["source"]) -> typing.Union['LLMSource', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["inference_framework"]) -> typing.Union[MetaOapg.properties.inference_framework, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["inference_framework_image_tag"]) -> typing.Union[MetaOapg.properties.inference_framework_image_tag, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["num_shards"]) -> typing.Union[MetaOapg.properties.num_shards, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["metadata"]) -> typing.Union[MetaOapg.properties.metadata, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["force_bundle_recreation"]) -> typing.Union[MetaOapg.properties.force_bundle_recreation, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["min_workers"]) -> typing.Union[MetaOapg.properties.min_workers, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["max_workers"]) -> typing.Union[MetaOapg.properties.max_workers, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["per_worker"]) -> typing.Union[MetaOapg.properties.per_worker, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["labels"]) -> typing.Union[MetaOapg.properties.labels, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["max_gpu_memory_utilization"]) -> typing.Union[MetaOapg.properties.max_gpu_memory_utilization, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["attention_backend"]) -> typing.Union[MetaOapg.properties.attention_backend, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["max_model_len"]) -> typing.Union[MetaOapg.properties.max_model_len, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["max_num_seqs"]) -> typing.Union[MetaOapg.properties.max_num_seqs, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["enforce_eager"]) -> typing.Union[MetaOapg.properties.enforce_eager, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["trust_remote_code"]) -> typing.Union[MetaOapg.properties.trust_remote_code, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["pipeline_parallel_size"]) -> typing.Union[MetaOapg.properties.pipeline_parallel_size, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["tensor_parallel_size"]) -> typing.Union[MetaOapg.properties.tensor_parallel_size, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["quantization"]) -> typing.Union[MetaOapg.properties.quantization, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["disable_log_requests"]) -> typing.Union[MetaOapg.properties.disable_log_requests, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["chat_template"]) -> typing.Union[MetaOapg.properties.chat_template, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["tool_call_parser"]) -> typing.Union[MetaOapg.properties.tool_call_parser, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["enable_auto_tool_choice"]) -> typing.Union[MetaOapg.properties.enable_auto_tool_choice, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["load_format"]) -> typing.Union[MetaOapg.properties.load_format, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["config_format"]) -> typing.Union[MetaOapg.properties.config_format, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["tokenizer_mode"]) -> typing.Union[MetaOapg.properties.tokenizer_mode, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["limit_mm_per_prompt"]) -> typing.Union[MetaOapg.properties.limit_mm_per_prompt, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["max_num_batched_tokens"]) -> typing.Union[MetaOapg.properties.max_num_batched_tokens, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["tokenizer"]) -> typing.Union[MetaOapg.properties.tokenizer, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["dtype"]) -> typing.Union[MetaOapg.properties.dtype, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["seed"]) -> typing.Union[MetaOapg.properties.seed, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["revision"]) -> typing.Union[MetaOapg.properties.revision, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["code_revision"]) -> typing.Union[MetaOapg.properties.code_revision, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["rope_scaling"]) -> typing.Union[MetaOapg.properties.rope_scaling, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["tokenizer_revision"]) -> typing.Union[MetaOapg.properties.tokenizer_revision, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["quantization_param_path"]) -> typing.Union[MetaOapg.properties.quantization_param_path, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["max_seq_len_to_capture"]) -> typing.Union[MetaOapg.properties.max_seq_len_to_capture, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["disable_sliding_window"]) -> typing.Union[MetaOapg.properties.disable_sliding_window, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["skip_tokenizer_init"]) -> typing.Union[MetaOapg.properties.skip_tokenizer_init, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["served_model_name"]) -> typing.Union[MetaOapg.properties.served_model_name, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["override_neuron_config"]) -> typing.Union[MetaOapg.properties.override_neuron_config, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["mm_processor_kwargs"]) -> typing.Union[MetaOapg.properties.mm_processor_kwargs, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["block_size"]) -> typing.Union[MetaOapg.properties.block_size, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["gpu_memory_utilization"]) -> typing.Union[MetaOapg.properties.gpu_memory_utilization, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["swap_space"]) -> typing.Union[MetaOapg.properties.swap_space, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["cache_dtype"]) -> typing.Union[MetaOapg.properties.cache_dtype, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["num_gpu_blocks_override"]) -> typing.Union[MetaOapg.properties.num_gpu_blocks_override, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["enable_prefix_caching"]) -> typing.Union[MetaOapg.properties.enable_prefix_caching, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["quantize", "checkpoint_path", "post_inference_hooks", "cpus", "gpus", "memory", "gpu_type", "storage", "nodes_per_worker", "optimize_costs", "prewarm", "high_priority", "billing_tags", "default_callback_url", "default_callback_auth", "public_inference", "chat_template_override", "enable_startup_metrics", "model_name", "source", "inference_framework", "inference_framework_image_tag", "num_shards", "metadata", "force_bundle_recreation", "min_workers", "max_workers", "per_worker", "labels", "max_gpu_memory_utilization", "attention_backend", "max_model_len", "max_num_seqs", "enforce_eager", "trust_remote_code", "pipeline_parallel_size", "tensor_parallel_size", "quantization", "disable_log_requests", "chat_template", "tool_call_parser", "enable_auto_tool_choice", "load_format", "config_format", "tokenizer_mode", "limit_mm_per_prompt", "max_num_batched_tokens", "tokenizer", "dtype", "seed", "revision", "code_revision", "rope_scaling", "tokenizer_revision", "quantization_param_path", "max_seq_len_to_capture", "disable_sliding_window", "skip_tokenizer_init", "served_model_name", "override_neuron_config", "mm_processor_kwargs", "block_size", "gpu_memory_utilization", "swap_space", "cache_dtype", "num_gpu_blocks_override", "enable_prefix_caching", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        quantize: typing.Union['Quantization', schemas.Unset] = schemas.unset,
        checkpoint_path: typing.Union[MetaOapg.properties.checkpoint_path, None, str, schemas.Unset] = schemas.unset,
        post_inference_hooks: typing.Union[MetaOapg.properties.post_inference_hooks, list, tuple, None, schemas.Unset] = schemas.unset,
        cpus: typing.Union[MetaOapg.properties.cpus, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
        gpus: typing.Union[MetaOapg.properties.gpus, None, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        memory: typing.Union[MetaOapg.properties.memory, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
        gpu_type: typing.Union['GpuType', schemas.Unset] = schemas.unset,
        storage: typing.Union[MetaOapg.properties.storage, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
        nodes_per_worker: typing.Union[MetaOapg.properties.nodes_per_worker, None, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        optimize_costs: typing.Union[MetaOapg.properties.optimize_costs, None, bool, schemas.Unset] = schemas.unset,
        prewarm: typing.Union[MetaOapg.properties.prewarm, None, bool, schemas.Unset] = schemas.unset,
        high_priority: typing.Union[MetaOapg.properties.high_priority, None, bool, schemas.Unset] = schemas.unset,
        billing_tags: typing.Union[MetaOapg.properties.billing_tags, dict, frozendict.frozendict, None, schemas.Unset] = schemas.unset,
        default_callback_url: typing.Union[MetaOapg.properties.default_callback_url, None, str, schemas.Unset] = schemas.unset,
        default_callback_auth: typing.Union['CallbackAuth', schemas.Unset] = schemas.unset,
        public_inference: typing.Union[MetaOapg.properties.public_inference, None, bool, schemas.Unset] = schemas.unset,
        chat_template_override: typing.Union[MetaOapg.properties.chat_template_override, None, str, schemas.Unset] = schemas.unset,
        enable_startup_metrics: typing.Union[MetaOapg.properties.enable_startup_metrics, None, bool, schemas.Unset] = schemas.unset,
        model_name: typing.Union[MetaOapg.properties.model_name, None, str, schemas.Unset] = schemas.unset,
        source: typing.Union['LLMSource', schemas.Unset] = schemas.unset,
        inference_framework: typing.Union[MetaOapg.properties.inference_framework, str, schemas.Unset] = schemas.unset,
        inference_framework_image_tag: typing.Union[MetaOapg.properties.inference_framework_image_tag, None, str, schemas.Unset] = schemas.unset,
        num_shards: typing.Union[MetaOapg.properties.num_shards, None, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        metadata: typing.Union[MetaOapg.properties.metadata, dict, frozendict.frozendict, None, schemas.Unset] = schemas.unset,
        force_bundle_recreation: typing.Union[MetaOapg.properties.force_bundle_recreation, None, bool, schemas.Unset] = schemas.unset,
        min_workers: typing.Union[MetaOapg.properties.min_workers, None, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        max_workers: typing.Union[MetaOapg.properties.max_workers, None, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        per_worker: typing.Union[MetaOapg.properties.per_worker, None, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        labels: typing.Union[MetaOapg.properties.labels, dict, frozendict.frozendict, None, schemas.Unset] = schemas.unset,
        max_gpu_memory_utilization: typing.Union[MetaOapg.properties.max_gpu_memory_utilization, None, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        attention_backend: typing.Union[MetaOapg.properties.attention_backend, None, str, schemas.Unset] = schemas.unset,
        max_model_len: typing.Union[MetaOapg.properties.max_model_len, None, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        max_num_seqs: typing.Union[MetaOapg.properties.max_num_seqs, None, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        enforce_eager: typing.Union[MetaOapg.properties.enforce_eager, None, bool, schemas.Unset] = schemas.unset,
        trust_remote_code: typing.Union[MetaOapg.properties.trust_remote_code, None, bool, schemas.Unset] = schemas.unset,
        pipeline_parallel_size: typing.Union[MetaOapg.properties.pipeline_parallel_size, None, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        tensor_parallel_size: typing.Union[MetaOapg.properties.tensor_parallel_size, None, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        quantization: typing.Union[MetaOapg.properties.quantization, None, str, schemas.Unset] = schemas.unset,
        disable_log_requests: typing.Union[MetaOapg.properties.disable_log_requests, None, bool, schemas.Unset] = schemas.unset,
        chat_template: typing.Union[MetaOapg.properties.chat_template, None, str, schemas.Unset] = schemas.unset,
        tool_call_parser: typing.Union[MetaOapg.properties.tool_call_parser, None, str, schemas.Unset] = schemas.unset,
        enable_auto_tool_choice: typing.Union[MetaOapg.properties.enable_auto_tool_choice, None, bool, schemas.Unset] = schemas.unset,
        load_format: typing.Union[MetaOapg.properties.load_format, None, str, schemas.Unset] = schemas.unset,
        config_format: typing.Union[MetaOapg.properties.config_format, None, str, schemas.Unset] = schemas.unset,
        tokenizer_mode: typing.Union[MetaOapg.properties.tokenizer_mode, None, str, schemas.Unset] = schemas.unset,
        limit_mm_per_prompt: typing.Union[MetaOapg.properties.limit_mm_per_prompt, None, str, schemas.Unset] = schemas.unset,
        max_num_batched_tokens: typing.Union[MetaOapg.properties.max_num_batched_tokens, None, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        tokenizer: typing.Union[MetaOapg.properties.tokenizer, None, str, schemas.Unset] = schemas.unset,
        dtype: typing.Union[MetaOapg.properties.dtype, None, str, schemas.Unset] = schemas.unset,
        seed: typing.Union[MetaOapg.properties.seed, None, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        revision: typing.Union[MetaOapg.properties.revision, None, str, schemas.Unset] = schemas.unset,
        code_revision: typing.Union[MetaOapg.properties.code_revision, None, str, schemas.Unset] = schemas.unset,
        rope_scaling: typing.Union[MetaOapg.properties.rope_scaling, dict, frozendict.frozendict, None, schemas.Unset] = schemas.unset,
        tokenizer_revision: typing.Union[MetaOapg.properties.tokenizer_revision, None, str, schemas.Unset] = schemas.unset,
        quantization_param_path: typing.Union[MetaOapg.properties.quantization_param_path, None, str, schemas.Unset] = schemas.unset,
        max_seq_len_to_capture: typing.Union[MetaOapg.properties.max_seq_len_to_capture, None, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        disable_sliding_window: typing.Union[MetaOapg.properties.disable_sliding_window, None, bool, schemas.Unset] = schemas.unset,
        skip_tokenizer_init: typing.Union[MetaOapg.properties.skip_tokenizer_init, None, bool, schemas.Unset] = schemas.unset,
        served_model_name: typing.Union[MetaOapg.properties.served_model_name, None, str, schemas.Unset] = schemas.unset,
        override_neuron_config: typing.Union[MetaOapg.properties.override_neuron_config, dict, frozendict.frozendict, None, schemas.Unset] = schemas.unset,
        mm_processor_kwargs: typing.Union[MetaOapg.properties.mm_processor_kwargs, dict, frozendict.frozendict, None, schemas.Unset] = schemas.unset,
        block_size: typing.Union[MetaOapg.properties.block_size, None, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        gpu_memory_utilization: typing.Union[MetaOapg.properties.gpu_memory_utilization, None, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        swap_space: typing.Union[MetaOapg.properties.swap_space, None, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        cache_dtype: typing.Union[MetaOapg.properties.cache_dtype, None, str, schemas.Unset] = schemas.unset,
        num_gpu_blocks_override: typing.Union[MetaOapg.properties.num_gpu_blocks_override, None, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        enable_prefix_caching: typing.Union[MetaOapg.properties.enable_prefix_caching, None, bool, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'UpdateVLLMModelEndpointRequest':
        return super().__new__(
            cls,
            *_args,
            quantize=quantize,
            checkpoint_path=checkpoint_path,
            post_inference_hooks=post_inference_hooks,
            cpus=cpus,
            gpus=gpus,
            memory=memory,
            gpu_type=gpu_type,
            storage=storage,
            nodes_per_worker=nodes_per_worker,
            optimize_costs=optimize_costs,
            prewarm=prewarm,
            high_priority=high_priority,
            billing_tags=billing_tags,
            default_callback_url=default_callback_url,
            default_callback_auth=default_callback_auth,
            public_inference=public_inference,
            chat_template_override=chat_template_override,
            enable_startup_metrics=enable_startup_metrics,
            model_name=model_name,
            source=source,
            inference_framework=inference_framework,
            inference_framework_image_tag=inference_framework_image_tag,
            num_shards=num_shards,
            metadata=metadata,
            force_bundle_recreation=force_bundle_recreation,
            min_workers=min_workers,
            max_workers=max_workers,
            per_worker=per_worker,
            labels=labels,
            max_gpu_memory_utilization=max_gpu_memory_utilization,
            attention_backend=attention_backend,
            max_model_len=max_model_len,
            max_num_seqs=max_num_seqs,
            enforce_eager=enforce_eager,
            trust_remote_code=trust_remote_code,
            pipeline_parallel_size=pipeline_parallel_size,
            tensor_parallel_size=tensor_parallel_size,
            quantization=quantization,
            disable_log_requests=disable_log_requests,
            chat_template=chat_template,
            tool_call_parser=tool_call_parser,
            enable_auto_tool_choice=enable_auto_tool_choice,
            load_format=load_format,
            config_format=config_format,
            tokenizer_mode=tokenizer_mode,
            limit_mm_per_prompt=limit_mm_per_prompt,
            max_num_batched_tokens=max_num_batched_tokens,
            tokenizer=tokenizer,
            dtype=dtype,
            seed=seed,
            revision=revision,
            code_revision=code_revision,
            rope_scaling=rope_scaling,
            tokenizer_revision=tokenizer_revision,
            quantization_param_path=quantization_param_path,
            max_seq_len_to_capture=max_seq_len_to_capture,
            disable_sliding_window=disable_sliding_window,
            skip_tokenizer_init=skip_tokenizer_init,
            served_model_name=served_model_name,
            override_neuron_config=override_neuron_config,
            mm_processor_kwargs=mm_processor_kwargs,
            block_size=block_size,
            gpu_memory_utilization=gpu_memory_utilization,
            swap_space=swap_space,
            cache_dtype=cache_dtype,
            num_gpu_blocks_override=num_gpu_blocks_override,
            enable_prefix_caching=enable_prefix_caching,
            _configuration=_configuration,
            **kwargs,
        )

from launch.api_client.model.callback_auth import CallbackAuth
from launch.api_client.model.gpu_type import GpuType
from launch.api_client.model.llm_source import LLMSource
from launch.api_client.model.quantization import Quantization
