# coding: utf-8

"""
    launch

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from launch.openapi_client.paths.healthcheck.get import (
    HealthcheckHealthcheckGet,
)
from launch.openapi_client.paths.healthz.get import HealthcheckHealthzGet
from launch.openapi_client.paths.readyz.get import HealthcheckReadyzGet
from launch.openapi_client.paths.v1_async_tasks.post import (
    CreateAsyncInferenceTaskV1AsyncTasksPost,
)
from launch.openapi_client.paths.v1_async_tasks_task_id.get import (
    GetAsyncInferenceTaskV1AsyncTasksTaskIdGet,
)
from launch.openapi_client.paths.v1_batch_jobs.post import (
    CreateBatchJobV1BatchJobsPost,
)
from launch.openapi_client.paths.v1_batch_jobs_batch_job_id.get import (
    GetBatchJobV1BatchJobsBatchJobIdGet,
)
from launch.openapi_client.paths.v1_batch_jobs_batch_job_id.put import (
    UpdateBatchJobV1BatchJobsBatchJobIdPut,
)
from launch.openapi_client.paths.v1_model_bundles.get import (
    ListModelBundlesV1ModelBundlesGet,
)
from launch.openapi_client.paths.v1_model_bundles.post import (
    CreateModelBundleV1ModelBundlesPost,
)
from launch.openapi_client.paths.v1_model_bundles_clone_with_changes.post import (
    CloneModelBundleWithChangesV1ModelBundlesCloneWithChangesPost,
)
from launch.openapi_client.paths.v1_model_bundles_latest.get import (
    GetLatestModelBundleV1ModelBundlesLatestGet,
)
from launch.openapi_client.paths.v1_model_bundles_model_bundle_id.get import (
    GetModelBundleV1ModelBundlesModelBundleIdGet,
)
from launch.openapi_client.paths.v1_model_endpoints.get import (
    ListModelEndpointsV1ModelEndpointsGet,
)
from launch.openapi_client.paths.v1_model_endpoints.post import (
    CreateModelEndpointV1ModelEndpointsPost,
)
from launch.openapi_client.paths.v1_model_endpoints_api.get import (
    GetModelEndpointsApiV1ModelEndpointsApiGet,
)
from launch.openapi_client.paths.v1_model_endpoints_model_endpoint_id.delete import (
    DeleteModelEndpointV1ModelEndpointsModelEndpointIdDelete,
)
from launch.openapi_client.paths.v1_model_endpoints_model_endpoint_id.get import (
    GetModelEndpointV1ModelEndpointsModelEndpointIdGet,
)
from launch.openapi_client.paths.v1_model_endpoints_model_endpoint_id.put import (
    UpdateModelEndpointV1ModelEndpointsModelEndpointIdPut,
)
from launch.openapi_client.paths.v1_model_endpoints_schema_json.get import (
    GetModelEndpointsSchemaV1ModelEndpointsSchemaJsonGet,
)
from launch.openapi_client.paths.v1_sync_tasks.post import (
    CreateSyncInferenceTaskV1SyncTasksPost,
)


class DefaultApi(
    CloneModelBundleWithChangesV1ModelBundlesCloneWithChangesPost,
    CreateAsyncInferenceTaskV1AsyncTasksPost,
    CreateBatchJobV1BatchJobsPost,
    CreateModelBundleV1ModelBundlesPost,
    CreateModelEndpointV1ModelEndpointsPost,
    CreateSyncInferenceTaskV1SyncTasksPost,
    DeleteModelEndpointV1ModelEndpointsModelEndpointIdDelete,
    GetAsyncInferenceTaskV1AsyncTasksTaskIdGet,
    GetBatchJobV1BatchJobsBatchJobIdGet,
    GetLatestModelBundleV1ModelBundlesLatestGet,
    GetModelBundleV1ModelBundlesModelBundleIdGet,
    GetModelEndpointV1ModelEndpointsModelEndpointIdGet,
    GetModelEndpointsApiV1ModelEndpointsApiGet,
    GetModelEndpointsSchemaV1ModelEndpointsSchemaJsonGet,
    HealthcheckHealthcheckGet,
    HealthcheckHealthzGet,
    HealthcheckReadyzGet,
    ListModelBundlesV1ModelBundlesGet,
    ListModelEndpointsV1ModelEndpointsGet,
    UpdateBatchJobV1BatchJobsBatchJobIdPut,
    UpdateModelEndpointV1ModelEndpointsModelEndpointIdPut,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    pass
