# coding: utf-8

"""
    launch

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import launch.api_client
from launch.api_client import configuration
from launch.api_client.model.create_docker_image_batch_job_bundle_v1_response import (
    CreateDockerImageBatchJobBundleV1Response,
)


class TestCreateDockerImageBatchJobBundleV1Response(unittest.TestCase):
    """CreateDockerImageBatchJobBundleV1Response unit test stubs"""

    _configuration = configuration.Configuration()


if __name__ == "__main__":
    unittest.main()
